(define (search-old function neg-value pos-value)
  (define (is-negative? function value) (< (function value) 0))
  (define (is-positive? function value) (> (function value) 0))
  (define (average x y) (/ (+ x y) 2.0))
  (define (decide-result average)
    (cond ((close-enough? function average) average)
	  ((is-negative? function average) (search-old function average pos-value))
	  ((is-positive? function average) (search-old function neg-value average))))
  (decide-result (average neg-value pos-value)))

(define (search-lambda function neg-value pos-value)
  (define (is-negative? function value) (< (function value) 0))
  (define (is-positive? function value) (> (function value) 0))
  (define (average x y) (/ (+ x y) 2.0))
  ((lambda (average)
     (cond ((close-enough? function average) average)
	   ((is-negative? function average) (search-lambda function average pos-value))
	   ((is-positive? function average) (search-lambda function neg-value average))))
   (average neg-value pos-value)))

(define (search-let function neg-value pos-value)
  (define (is-negative? function value) (< (function value) 0))
  (define (is-positive? function value) (> (function value) 0))
  (define (average x y) (/ (+ x y) 2.0))
  (let ((avg (average neg-value pos-value)))
    (cond ((close-enough? function avg) avg)
	  ((is-negative? function avg) (search-let function avg pos-value))
	  ((is-positive? function avg) (search-let function neg-value avg)))))
